EvaCity/Models/Entidades/Proyecto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EvaCity.Models.Entidades
{
    public class Proyecto
    {
        public int ProyectoId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaCreacion { get; set; }
        public DateTime FechaModificacion { get; set; }

        public string UsuarioId { get; set; }
        public virtual ApplicationUser Usuario { get; set; }
        
        public int SeccionId { get; set; }
        public virtual Seccion Seccion { get; set; }

        public int CiudadId { get; set; }
        public virtual Ciudad Ciudad { get; set; }

        //public int EstadoId { get; set; }
        //public virtual Estado Estado { get; set; }

        public virtual IList<Valoracion> Valoraciones { get; set; }
    }
}

EvaCity/Models/ViewModels/InformacionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EvaCity.Models.ViewModels
{
    public class InformacionViewModel
    {
        public IList<ProyectoViewModel> proyectosViewModel { get; set; }
        public IList<UbicacionViewModel> ubicacionesViewModel { get; set; }
        public IList<CiudadViewModel> ciudadesViewModel { get; set; }
        public UsuarioViewModel usuarioViewModel { get; set; }
    }
}

EvaCity/Models/ViewModels/ProyectoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EvaCity.Models.ViewModels
{
    public class ProyectoViewModel
    {
        [Required(ErrorMessage = "Introduce un nombre para el proyecto.")]
        [Display(Name = "Nombre")]
        [DataType(DataType.Text)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Introduce una descripción para el proyecto.")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

        [Display(Name = "Fecha de creación")]
        public DateTime FechaCreacion { get; set; }

        [Display(Name = "Fecha de modificación")]
        public DateTime FechaModificacion { get; set; }

        //[Required(ErrorMessage = "Introduce un usuario.")]
        [Display(Name = "Usuario")]
        public string NombreUsuario { get; set; }

        [Display(Name = "Sección")]
        public string NombreSeccion { get; set; }

        [Display(Name = "Sección")]
        public string SeccionSeleccionada { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Secciones { get; set; }

        public int ProyectoId { get; set; }

        [Display(Name = "Ciudad")]
        public string NombreCiudad { get; set; }

        [Display(Name = "Ciudad")]
        public string CiudadSeleccionada { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Ciudades { get; set; }

        public int VotosPositivos { get; set; }

        public int VotosNegativos { get; set; }

        public bool Editable { get; set; }
        public bool EsAP { get; set; }
    }
}

EvaCity/Controllers/ProyectoController.cs
using EvaCity.Models.Entidades;
using EvaCity.Models.ViewModels;
using EvaCity.Servicios;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaCity.Controllers
{
    public class ProyectoController : Controller
    {
        private ProyectoServicio proyectoServicio = new ProyectoServicio();
        private CiudadServicio ciudadServicio = new CiudadServicio();
        private SeccionServicio seccionServicio = new SeccionServicio();
        private UsuarioServicio usuarioServicio = new UsuarioServicio();
        private ValoracionServicio valoracionServicio = new ValoracionServicio();
        private TipoUbicacionServicio tipoUbicacionServicio = new TipoUbicacionServicio();
        private UbicacionServicio ubicacionServicio = new UbicacionServicio();

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Proyecto
        public ActionResult Index()
        {
            return View();
        }

        //Listado de proyectos
        public ActionResult Informacion(int seccion, string ciudad)
        {
            if (System.Web.HttpContext.Current.Session != null)
            {
                System.Web.HttpContext.Current.Session["idSeccion"] = seccion;
            }

            //Tipo de seccion
            if (seccion == 1)
            {
                ViewBag.Seccion = "Contaminacion";
            }
            else if (seccion == 2)
            {
                ViewBag.Seccion = "Energías Renovables";
            }
            else if (seccion == 3)
            {
                ViewBag.Seccion = "Reciclaje";
            }
            else if (seccion == 4)
            {
                ViewBag.Seccion = "Movilidad Sostenible";
            }
            else if (seccion == 5)
            {
                ViewBag.Seccion = "Negocios Sostenibles";
            }

            IList<Proyecto> listadoProyectos = new List<Proyecto>();
            IList<Ubicacion> listadoEmpresas = new List<Ubicacion>();
            IList<Ciudad> listadoCiudades = new List<Ciudad>();

            InformacionViewModel infoVM = new InformacionViewModel();
            UsuarioViewModel usuarioVM = new UsuarioViewModel();

            if (User.Identity.GetUserId() != null)
            {
                usuarioVM.CiudadUsuario = ciudadServicio.ObtenerCiudadPorId(usuarioServicio.ObtenerIdCiudadUsuario(User.Identity.GetUserId())).Nombre;
                infoVM.usuarioViewModel = usuarioVM;
            }

            infoVM.proyectosViewModel = new List<ProyectoViewModel>();
            infoVM.ubicacionesViewModel = new List<UbicacionViewModel>();
            infoVM.ciudadesViewModel = new List<CiudadViewModel>();

            if (ciudad != null)
            {
                listadoProyectos = proyectoServicio.ObtenerProyectosPorSeccionYCiudad(seccion, ciudadServicio.ObtenerCiudadPorNombre(ciudad).CiudadId);
                listadoEmpresas = ubicacionServicio.ObtenerEmpresas(ciudad);
            }
            else
            {
                listadoProyectos = proyectoServicio.ObtenerProyectosPorSeccion(seccion);
                listadoEmpresas = ubicacionServicio.ObtenerTodasEmpresas();
            }

            foreach (var proyecto in listadoProyectos)
            {
                ProyectoViewModel proyectoVM = new ProyectoViewModel();
                proyectoServicio.ProyectoModelToViewModel(proyectoVM, proyecto);
                if (usuarioServicio.ObtenerUsuarioPorNombre(proyectoVM.NombreUsuario).Id == User.Identity.GetUserId()) {
                    proyectoVM.Editable = true;
                }
                if (UserManager.IsInRole(usuarioServicio.ObtenerUsuarioPorNombre(proyectoVM.NombreUsuario).Id, "Administracion Publica")) {
                    proyectoVM.EsAP = true;
                }
                infoVM.proyectosViewModel.Add(proyectoVM);
            }
            foreach (var empresa in listadoEmpresas)
            {
                UbicacionViewModel empresaVM = new UbicacionViewModel();
                ubicacionServicio.UbicacionModelToViewModel(empresaVM, empresa);
                infoVM.ubicacionesViewModel.Add(empresaVM);
            }

            listadoCiudades = ciudadServicio.ObtenerTodasCiudades();

            foreach (var ciudadModel in listadoCiudades)
            {
                CiudadViewModel ciudadVM = new CiudadViewModel();
                ciudadVM.Proyectos = proyectoServicio.ObtenerProyectosPorSeccionYCiudad(seccion, ciudadModel.CiudadId);
                ciudadServicio.CiudadModelToViewModel(ciudadVM, ciudadModel);
                infoVM.ciudadesViewModel.Add(ciudadVM);
            }
            var ciudades = infoVM.ciudadesViewModel.OrderByDescending(v => v.Valoracion).ToList();
            infoVM.ciudadesViewModel = ciudades;

            var todosTiposUbicaciones = tipoUbicacionServicio.ObtenerTodosTipoUbicacion();
            var factorOptions = todosTiposUbicaciones.Select(tiposUbicaciones => new SelectListItem { Text = tiposUbicaciones.Nombre, Value = tiposUbicaciones.TipoUbicacionId.ToString() }).ToList();

            var tuple = new Tuple<InformacionViewModel, TipoUbicacionViewModel>(infoVM, new TipoUbicacionViewModel { TiposUbicaciones = factorOptions });

            return View(tuple);
        }
        public ActionResult ActualizarRanking(SeccionViewModel seccionVM) {
            InformacionViewModel infoVM = new InformacionViewModel();
            IList<Ciudad> listadoCiudades = new List<Ciudad>();

            infoVM.ciudadesViewModel = new List<CiudadViewModel>();
            listadoCiudades = ciudadServicio.ObtenerTodasCiudades();

            foreach (var ciudadModel in listadoCiudades)
            {
                CiudadViewModel ciudadVM = new CiudadViewModel();
                ciudadVM.Proyectos = proyectoServicio.ObtenerProyectosPorSeccionYCiudad(Int32.Parse(System.Web.HttpContext.Current.Session["idSeccion"].ToString()), ciudadModel.CiudadId);
                ciudadServicio.CiudadModelToViewModel(ciudadVM, ciudadModel);
                infoVM.ciudadesViewModel.Add(ciudadVM);
            }
            var ciudades = infoVM.ciudadesViewModel.OrderByDescending(v => v.Valoracion).ThenByDescending(c => c.VotosTotales).ToList();
            infoVM.ciudadesViewModel = ciudades;

            UsuarioViewModel usuarioVM = new UsuarioViewModel();

            if (User.Identity.GetUserId() != null)
            {
                usuarioVM.CiudadUsuario = ciudadServicio.ObtenerCiudadPorId(usuarioServicio.ObtenerIdCiudadUsuario(User.Identity.GetUserId())).Nombre;
                infoVM.usuarioViewModel = usuarioVM;
            }

            return Json(infoVM);
        }

        public ActionResult BuscarProyectosAP(ProyectoViewModel model)
        {
            //System.Web.HttpContext.Current.Session["idSeccion"] =;

            IList<Proyecto> listadoProyectos = new List<Proyecto>();

            listadoProyectos = proyectoServicio.ObtenerProyectosAP();
            //if (ciudad != null)
            //{
            //    listadoProyectos = proyectoServicio.ObtenerProyectosPorSeccionYCiudad(seccion, ciudadServicio.ObtenerCiudadPorNombre(ciudad).CiudadId);
            //}
            //else
            //{
            //    listadoProyectos = proyectoServicio.ObtenerProyectosPorSeccion(seccion);
            //}

            IList<ProyectoViewModel> listaViewProyecto = new List<ProyectoViewModel>();

            foreach (var proyecto in listadoProyectos)
            {
                ProyectoViewModel proyectoVM = new ProyectoViewModel();
                proyectoServicio.ProyectoModelToViewModel(proyectoVM, proyecto);
                listaViewProyecto.Add(proyectoVM);
            }


            var todosTiposUbicaciones = tipoUbicacionServicio.ObtenerTodosTipoUbicacion();
            var factorOptions = todosTiposUbicaciones.Select(tiposUbicaciones => new SelectListItem { Text = tiposUbicaciones.Nombre, Value = tiposUbicaciones.TipoUbicacionId.ToString() }).ToList();

            var tuple = new Tuple<IList<ProyectoViewModel>, UbicacionViewModel>(listaViewProyecto, new UbicacionViewModel { TiposUbicaciones = factorOptions });

            //return View(tuple);
            return RedirectToAction("Informacion", new { seccion = System.Web.HttpContext.Current.Session["idSeccion"] });
        }

        // GET: /Proyecto/NuevoProyecto
        public ActionResult NuevoProyecto()
        {
            var todasCiudades = ciudadServicio.ObtenerTodasCiudades();
            var ciudadesModel = todasCiudades.Select(ciudades => new SelectListItem { Text = ciudades.Nombre, Value = ciudades.CiudadId.ToString() }).ToList();
            return View(new ProyectoViewModel { Ciudades = ciudadesModel });
        }

        // POST: /Proyecto/NuevoProyecto
        [HttpPost()]
        public ActionResult NuevoProyecto(ProyectoViewModel proyectoVM)
        {
            if (!ModelState.IsValid)
                return View(proyectoVM);

            Proyecto proyecto = new Proyecto();

            proyecto.Nombre = proyectoVM.Nombre;
            proyecto.Descripcion = proyectoVM.Descripcion;
            proyecto.CiudadId = ciudadServicio.ObtenerCiudadPorId(Int32.Parse(proyectoVM.CiudadSeleccionada)).CiudadId;
            proyecto.FechaCreacion = DateTime.Now;
            proyecto.FechaModificacion = DateTime.Now;
            proyecto.SeccionId = (int)System.Web.HttpContext.Current.Session["idSeccion"];
            proyecto.UsuarioId = User.Identity.GetUserId();
            
            var ciudadActual = "";

EvaCity/Views/Proyecto/Detalles.cshtml
@model EvaCity.Models.ViewModels.ProyectoViewModel

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>
@*@{
    var valueCiudad = "";
    if (System.Web.HttpContext.Current.Session["ciudad"] != null)
    {
        valueCiudad = System.Web.HttpContext.Current.Session["ciudad"].ToString();
    }
    var seccion = Session["idSeccion"];
}*@

<div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel-group">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h4 class="panel-title">@Html.DisplayFor(model => model.Nombre)</h4>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3">
                                <label>@Html.DisplayNameFor(model => model.FechaCreacion)</label>
                            </div>
                            <div class="col-md-3">
                                @Html.DisplayFor(model => model.FechaCreacion)
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <label>@Html.DisplayNameFor(model => model.NombreCiudad)</label>
                            </div>
                            <div class="col-md-3">
                                @Html.DisplayFor(model => model.NombreCiudad)
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <label>@Html.DisplayNameFor(model => model.NombreUsuario)</label>
                            </div>
                            <div class="col-md-3">
                                @Html.DisplayFor(model => model.NombreUsuario)
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <label>@Html.DisplayNameFor(model => model.Descripcion)</label>
                            </div>
                            <div class="col-md-3 truncate">
                                @Html.DisplayFor(model => model.Descripcion)
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @if (User.IsInRole("Administrador") || Model.Editable == true)
            {
            <button type="submit" class="btn btn-warning" onclick="location.href='@Url.Action("EditarProyecto", "Proyecto", new { id = Model.ProyectoId })'">
                Editar
            </button>
            }
            <input type="submit" value="Volver" class="btn btn-danger" onclick="location.href='@Url.Action("Informacion","Proyecto", new { seccion = Session["idSeccion"], ciudad = Session["ciudad"] })'" />
        </div>
    </div>
</div>

EvaCity/Views/Proyecto/EditarProyecto.cshtml
@model EvaCity.Models.ViewModels.ProyectoViewModel

@{
    ViewBag.Title = "Editar Proyecto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Proyecto</h2>

@*@{
    var valueCiudad = "";
    if (System.Web.HttpContext.Current.Session["ciudad"] != null)
    {
        valueCiudad = System.Web.HttpContext.Current.Session["ciudad"].ToString();
    }
}*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ProyectoId)
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SeccionSeleccionada, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.SeccionSeleccionada, Model.Secciones, new { @class = "form-control dropdown", @id = "seccionSeleccionada" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CiudadSeleccionada, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.CiudadSeleccionada, Model.Ciudades, new { @class = "form-control dropdown", @id = "ciudadSeleccionada" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
                <input type="button" value="Cancelar" class="btn btn-danger" onclick="location.href='@Url.Action("Informacion","Proyecto", new { seccion = Session["idSeccion"], ciudad = Session["ciudad"] })'" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EvaCity/Views/Proyecto/NuevoProyecto.cshtml
@model EvaCity.Models.ViewModels.ProyectoViewModel

@{
    ViewBag.Title = "Nuevo Proyecto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo Proyecto</h2>

@{
    var valueCiudad = "";
    if (System.Web.HttpContext.Current.Session["ciudad"] != null)
    {
        valueCiudad = System.Web.HttpContext.Current.Session["ciudad"].ToString();
    }
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
  
        @*@Html.HiddenFor(model => model.NombreUsuario, @User.Identity.Name)*@
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CiudadSeleccionada, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CiudadSeleccionada, Model.Ciudades, new { @class = "form-control dropdown", @id = "ciudadSeleccionada" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Proyecto" class="btn btn-success" />
                <input type="button" value="Cancelar" class="btn btn-danger" onclick="location.href='@Url.Action("Informacion","Proyecto", new { seccion = Session["idSeccion"], ciudad = valueCiudad })'" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
}