EvaCity/Models/ViewModels/CuentaViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EvaCity.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "El Email introducido no es válido.")]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "La contraseña introducida no es válida.")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Recuérdame")]
        public bool RememberMe { get; set; }
    }

    public class RegistroViewModel
    {
        [Required]
        [StringLength(50, ErrorMessage = "La {0} debe tener al menos {2} caracteres de longitud.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Nombre de usuario")]
        public string Nombre { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "La {0} debe tener al menos {2} caracteres de longitud.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar password")]
        [Compare("Password", ErrorMessage = "La contraseña y la contraseña de confirmación no coinciden.")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Administracion Pública")]
        public bool Perfil { get; set; }

        [Required]
        [Display(Name = "Fecha de nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        [Display(Name = "Ciudad")]
        public string CiudadSeleccionada { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Ciudades { get; set; }
    }
}

EvaCity/Controllers/CuentaController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using EvaCity.Models;
using EvaCity.Servicios;
using System;

namespace EvaCity.Controllers
{
    [Authorize]
    public class CuentaController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private CiudadServicio ciudadServicio = new CiudadServicio();

        public CuentaController()
        {
        }

        public CuentaController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = UserManager.FindByEmail(model.Email);

            if (user == null) {
                user = new ApplicationUser();
                user.UserName = "";
            }

            var result = await SignInManager.PasswordSignInAsync(user.UserName, model.Password, model.RememberMe, shouldLockout: false);

            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "El usuario o la contraseña no son correctos.");
                    return View(model);
            }
        }

        [AllowAnonymous]
        public ActionResult Registro()
        {
            var todasCiudades = ciudadServicio.ObtenerTodasCiudades();
            var ciudadesModel = todasCiudades.Select(ciudades => new SelectListItem { Text = ciudades.Nombre, Value = ciudades.CiudadId.ToString() }).ToList();
            return View(new RegistroViewModel { Ciudades = ciudadesModel });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Registro(RegistroViewModel model)
        {
            var todasCiudades = ciudadServicio.ObtenerTodasCiudades();
            var ciudadesModel = todasCiudades.Select(ciudades => new SelectListItem { Text = ciudades.Nombre, Value = ciudades.CiudadId.ToString() }).ToList();
            model.Ciudades = ciudadesModel;

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Nombre, Email = model.Email };
                user.CiudadId = ciudadServicio.ObtenerCiudadPorId(Int32.Parse(model.CiudadSeleccionada)).CiudadId;
                user.FechaNacimiento = model.FechaNacimiento.ToString("yyyy-MM-dd");
                var result = await UserManager.CreateAsync(user, model.Password);

                if (model.Perfil)
                {
                    UserManager.AddToRole(user.Id, "Administracion Publica");
                    user.Perfil = "Administracion Publica";
                }
                else
                {
                    UserManager.AddToRole(user.Id, "Ciudadano");
                    user.Perfil = "Ciudadano";
                }
                user.EmailConfirmed = true;
                user.LockoutEnabled = false;
                UserManager.Update(user);

                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult ResetPasswordConfirmation()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_userManager != null)
                {
                    _userManager.Dispose();
                    _userManager = null;
                }

                if (_signInManager != null)
                {
                    _signInManager.Dispose();
                    _signInManager = null;
                }
            }

            base.Dispose(disposing);
        }

        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        internal class ChallengeResult : HttpUnauthorizedResult
        {
            public ChallengeResult(string provider, string redirectUri)
                : this(provider, redirectUri, null)
            {
            }

            public ChallengeResult(string provider, string redirectUri, string userId)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
                UserId = userId;
            }

            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }
            public string UserId { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                if (UserId != null)
                {
                    properties.Dictionary[XsrfKey] = UserId;
                }
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }
        #endregion
    }
}

EvaCity/Views/Cuenta/Login.cshtml
@using EvaCity.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
}

<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <h2 class="text-center">@ViewBag.Title</h2>    
    </div>
    <div class="col-md-3">
    </div>
</div>

<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Cuenta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.RememberMe, new { @class = "control-label" })
                    </div>
                    <div class="col-md-8">
                        @Html.CheckBoxFor(m => m.RememberMe)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Entrar" class="btn btn-success" />
                        <input class="btn btn-danger cancelar" value="Cancelar" onclick="location.href='@Url.Action("Index","Home")'" />
                    </div>
                </div>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
    <div class="col-md-3">
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EvaCity/Views/Cuenta/Registro.cshtml
@model EvaCity.Models.RegistroViewModel
@{
    ViewBag.Title = "Registrarse";
}

@using (Html.BeginForm("Registro", "Cuenta", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <h2>@ViewBag.Title</h2>
            <hr />
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Nombre, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.FechaNacimiento, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", type = "date" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CiudadSeleccionada, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(m => m.CiudadSeleccionada, Model.Ciudades, new { @class = "form-control dropdown", @id = "ciudadSeleccionada" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Perfil, new { @class = "col-md-4 control -label" })
                <div class="col-md-8">
                    @Html.CheckBoxFor(m => m.Perfil, new { @class = "checkbox" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-6 col-md-10">
                    <input type="submit" class="btn btn-success" value="Registro" />
                    <input type="button" class="btn btn-danger" value="Cancelar" onclick="location.href='@Url.Action("Index","Home")'" />
                </div>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}